firstproj/firstapp/urls.py
from django.urls import path
from firstapp import views

app_name='firstapp'

urlpatterns = [
    path('user_login/',views.user_login,name='user_login'),
    path('register/',views.register,name='register'),
]

# In base.html file <!--{% url 'app_name define in urls.py file:name of the url (name='user_login') %}-->

firstproj/firstproj/urls.py
from django.contrib import admin
from django.urls import path,include
from firstapp import views 


urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('',include('firstapp.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

firstproj/firstapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional classess

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pic',blank=True)

    def __str__(self):
        return self.user.username

firstproj/firstapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

firstproj/firstapp/views.py
from django.shortcuts import render
from firstapp.forms import UserProfileInfoForm,UserForm

#django builtin functionality

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    return render(request,'index.html')

@login_required
def special(request):
    return HttpResponse('You are logged in , Nice !')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})
    

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username') # username is value of name in input tags on html page 
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:

            login(request,user) # pass the request and user object of authenticate
            return HttpResponseRedirect(reverse('index'))

            '''if user.is_active():
                login(request,user) # pass the request and user object of authenticate
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account Not Active')'''
        else:
            print('Someone tried to login and failed')
            print('username: {} and password {}'.format(username,password))
            return HttpResponse('invalid login details supplied!')

    else:
        return render(request,'login.html',{})

firstproj/firstapp/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='uft-8'>
        <title></title>
        <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
        <nav class='navbar navbar-default navbar-static-top'>
            <div class='container'>
                <ul class='nav navbar-nav'>
                    <li><a class='navbar-brand' href='{% url "index" %}'>DJANGO</a></li>
                    <li><a class='navbar-link' href='{% url "admin:index" %}'>Admin</a></li>
                    <li><a class='navbar-link' href='{% url "firstapp:register" %}'>Register</a></li>

                    {% if user.is_authenticated %}
                    <li><a class='navbar-link' href='{% url "logout" %}'>Logout</a></li>
                    {% else %}
                    
                    <li><a class='navbar-link' href='{% url "firstapp:user_login" %}'>Login</a></li> 
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class='container'>
            {% block context %}
            <!--Anything outside of this will be inherited if you extends!-->
            {% endblock %}
        </div>
    </body>
</html>

firstproj/firstapp/templates/index.html
{% extends 'base.html' %}

{% block context %}

<div class='jumbotron'>
    <h1>Django Level Five Index</h1>
</div>

{% endblock %}

firstproj/firstapp/templates/login.html
{% extends 'base.html' %}

{% block context %}

<div class='jumbotron'>
    <h1>Please Login!</h1>
    <form action='{% url "firstapp:user_login" %}' method="POST">
        {% csrf_token %}
        <lable for='username'>Username:</lable>
        <input type='text' name='username' placeholder="Enter Username">

        <lable for='password'>Password:</lable>
        <input type='password' name='password'>

        <input type='submit' name='' value='Login'>

    </form>
</div>

{% endblock %}

firstproj/firstapp/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% block context %}

<div class='jumbotron'>
    {% if registered %}
    <h1>Thank you for registering!</h1>

    {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>

    <form enctype="multipart/form-data" method='POST'>
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}

        <input type='submit' name='' value='Register'>
        </form>
        {% endif %}
</div>

{% endblock %}